twig:
    file_name_pattern: '*.twig'
    form_themes: ["bootstrap_5_layout.html.twig"]
    globals:
        companyRepository: '@App\Repository\CompanyRepository'
        appName: "L'ODYSSÃ‰E DES NOMBRES"

when@test:
    twig:
        strict_variables: true
