vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       about_images:
           uri_prefix: /images/about
           upload_destination: '%kernel.project_dir%/public/images/about'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       links_svg:
           uri_prefix: /images/links
           upload_destination: '%kernel.project_dir%/public/images/links'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       categories_svg:
           uri_prefix: /images/categories
           upload_destination: '%kernel.project_dir%/public/images/categories'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       avatars_images:
           uri_prefix: /images/avatars
           upload_destination: '%kernel.project_dir%/public/images/avatars'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       appointments_images:
           uri_prefix: /images/appointments
           upload_destination: '%kernel.project_dir%/public/images/appointments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
       appointment_pdf:
           uri_prefix: /doc/appointments
           upload_destination: '%kernel.project_dir%/public/doc/appointments'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
