# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    avatars_directory: '%kernel.project_dir%/public/images/avatars'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\SendMailService:
        arguments:
            $defaultFrom: "%env(MAILER_DEFAULT_FROM)%"

    App\EventDispatcher\ContactEmailSuccessSubscriber:
        arguments:
            $defaultFrom: "%env(MAILER_DEFAULT_FROM)%"

    App\EventDispatcher\AppointmentEmailSuccessSubscriber:
        arguments:
            $defaultFrom: "%env(MAILER_DEFAULT_FROM)%"

    App\EventDispatcher\AppointmentEmailCancelledSubscriber:
        arguments:
            $defaultFrom: "%env(MAILER_DEFAULT_FROM)%"

    App\EventDispatcher\AppointmentEmailRescheduledSubscriber:
        arguments:
            $defaultFrom: "%env(MAILER_DEFAULT_FROM)%"

    App\Google\GoogleService:
        arguments:
            $googleKey: "%env(GOOGLE_API_KEY)%"

    auth_mailer:
        class: App\Service\SendEmail2faService

    App\Stripe\StripeService:
        arguments:
            $secretKey: '%env(STRIPE_SECRET_KEY)%'
            $publicKey: '%env(STRIPE_PUBLIC_KEY)%'
